"""
Source code file for my basic notes app using Tkinter.
This file manages the database operations for the notes app.
This includes creating the database, adding, retrieving, updating, and deleting notes.
"""

import qanotz.utils.os as os_utils
from qanotz.data.parser import parse
from qanotz.utils.filesystem import File, QAFile

class DataManagerInstance:
    def __init__(self, file_loc: str) -> None:
        appdata_dir = os_utils.get_appdata_dir()
        self.data_path = f"{appdata_dir}/qanotz"

        os_utils.ensure_dir(self.data_path)

        self.file = File(self.data_path + file_loc)

        try:
            self.file.read()
        except Exception:
            self.file.write('')

class LogManagerInstance(DataManagerInstance):
    def __init__(self) -> None:
        self.log_file = "/qalogs.log"
        super().__init__(self.log_file)

    def log_message(self, msg: str):
        self.file.append("\n" + msg)
        print(self.file.read())

class DatabaseManagerInstance(DataManagerInstance):
    def __init__(self):
        self.db_lookup = "/dblookup.dbl"
        super().__init__(self.db_lookup)

        os_utils.ensure_dir(self.data_path + '/qafiles')

    def parse_lookup(self):
        pass

    def create_qafile(self, content: str):
       qafile = QAFile(f"{self.data_path}/qafiles/{os_utils.generate_random_filename()}.qan")

if __name__ == "__main__":
    db = DatabaseManagerInstance()
    log = LogManagerInstance()

    print(f"Database initialized at: {db.file.path}")
    print(f"Log file is located at: {log.file.path}")

    log.log_message("This message was autogenerated while testing the LogManagerInstance in QANotz.")
